version: 1.0

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
    post_build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    - target/sample-code-build-1.jar
  discard-paths: yes